# Generated by Django 5.0.6 on 2024-06-20 16:17

import django.db.models.deletion
import logistics.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=225)),
                ('sender_address', models.TextField()),
                ('receiver_name', models.CharField(max_length=225)),
                ('receiver_address', models.TextField()),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_notes', models.TextField()),
                ('delivery_type', models.CharField(choices=[('E', 'EXPRESS'), ('S', 'STANDARD')], default='E', max_length=1)),
                ('pickup_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.TextField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('availability', models.BooleanField(default=True)),
                ('driver_address', models.TextField(max_length=255)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=logistics.utility.generate_tracking_number, max_length=15, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='P', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliveryInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.deliveryinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.package')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.driver')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='logistics.tracker')),
            ],
        ),
    ]
